# Generated by Django 5.2.10 on 2026-02-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='num_ingredients',
            field=models.CharField(max_length=50),
        ),
    ]
