# Generated by Django 6.0 on 2026-03-12 16:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recipe_created_on_recipe_updated_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(255, 'the field must contain at least 255 characters')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('short_description', models.TextField(validators=[django.core.validators.MinLengthValidator(255, 'the field must contain at least 255 characters')])),
                ('recipe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_image', to='ledger.recipe')),
            ],
        ),
    ]
