# Generated by Django 6.0 on 2026-03-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_profile_short_bio_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeimage',
            options={'verbose_name': 'recipe_pictures', 'verbose_name_plural': 'recipe_pictures'},
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='short_description',
            field=models.TextField(max_length=255),
        ),
    ]
